# Generated by Django 3.1.3 on 2022-08-18 03:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('onlinecourse', '0004_auto_20220809_0222'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='question_grade',
            field=models.IntegerField(),
        ),
    ]
