# Generated by Django 3.1.3 on 2022-08-18 03:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('onlinecourse', '0005_auto_20220818_0331'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='question_grade',
            field=models.FloatField(),
        ),
    ]
